### ISSUE TITLE
Links doesn't work in Desktop and Mobile Safari

### ISSUE THREAD

**Issue by bartoszmagier** [samthor/rippleJS#4]
Links on `<a>` elements does not work in Safari when using rippleJS. Is there any fix for this?

**Comment by samthor** [comment]
It seems to work fine on <a> elements on Safari on Mac. Admittedly, without styling the link, the ripple expands to the whole page - as per the README.md, you need to give the link layout-

> Then, add element with the rippleJS class within a parent element that has layout (aka, position: relative or position: absolute).

As for Mobile, I have the same experience - I'm using the iOS simulator, to load test.html, and that works fine.

Can you elaborate?

**Comment by bartoszmagier** [comment]
@samthor I'm not talking about the ripple effect. Links don't redirect the user after the click (bug tested only on desktop Safari 10.0.2 and mobile browsers).

**Comment by samthor** [comment]
Sorry, I can't repro. See screenshots-

![screen shot 2017-01-18 at 10 44 38](https://cloud.githubusercontent.com/assets/119184/22045132/9feaadcc-dd6c-11e6-99a7-68375b35ddc8.png)

![screen shot 2017-01-18 at 10 44 48](https://cloud.githubusercontent.com/assets/119184/22045130/9e505322-dd6c-11e6-8a90-d7e226a48c61.png)

(You probably don't need a 3rd shot of what Google looks like :) )

**Comment by samthor** [comment]
So this issue was that I was suggesting to use a `<link class="rippleJS" />` element to contain the ripple. Turns out Safari wasn't happy with this, and was eating the click on the `link` element.

I've updated the docs to suggest using a plain-old `<div class="rippleJS"></div>` now.
