### ISSUE TITLE
Demos buttons don't work

### ISSUE THREAD

**Issue by Wapweb** [samthor/rippleJS#6]
Hey, thanks for good library. Buttons in demo don't work in Firefox v54.0.1 64 bit (but list items ripple effect works fine)
In Google Chrome everything is ok
Updated:
![untitled](https://user-images.githubusercontent.com/8421581/28037606-8ea7611e-65c4-11e7-8ffc-f2538d8b1da6.png)

I figured it out. The problem is related to firefox bug about referring event.target to parent button element:  https://bugzilla.mozilla.org/show_bug.cgi?id=1089326
I've already made the [PR](https://github.com/samthor/rippleJS/pull/7) that resolves issue

**Comment by samthor** [comment]
Fixed by #7
