### ISSUE TITLE
add init method for delayed loading

### ISSUE THREAD

**Issue by AaronLayton** [samthor/rippleJS#8]
Great work on this module, nice and performant and handles multiple ripples with ease.

I am delaying the loading of this module until after window load as its not critical but most of the script runs on the load event.

Could it be updated to have an `init()` method that is ran on window load or ran when it has been loaded in in the above use case

**Comment by AmirSavand** [comment]
+1 for `ng-repeat` in `AngularJS`.

**Comment by samthor** [comment]
I've exported the code inside [lib.js](https://github.com/samthor/rippleJS/blob/master/lib.js) so you could include the code into your own projects. You just need to run the default method from lib, and include the CSS (see [ripple.js](https://github.com/samthor/rippleJS/blob/master/ripple.js) for how I do this).
